"""Stable evidence capability enums."""

from enum import StrEnum


class ChampionPolicyCode(StrEnum):
    INVALID_VERIFICATION_SET = "CHAMPION_INVALID_VERIFICATION_SET"
    UNSTABLE_ENVIRONMENT = "CHAMPION_UNSTABLE_ENVIRONMENT"
    INSUFFICIENT_IMPROVEMENT = "CHAMPION_INSUFFICIENT_IMPROVEMENT"


class EvidenceValidationCode(StrEnum):
    PROVIDER_UNAVAILABLE = "EVIDENCE_PROVIDER_UNAVAILABLE"
    PROFILE_UNVERIFIED = "EVIDENCE_PROFILE_UNVERIFIED"
    IDEMPOTENCY_CONFLICT = "EVIDENCE_IDEMPOTENCY_CONFLICT"
    RUN_NOT_FOUND = "EVIDENCE_RUN_NOT_FOUND"
    PROVIDER_REJECTED = "EVIDENCE_PROVIDER_REJECTED"
    INVALID_PROVIDER_STATE = "EVIDENCE_INVALID_PROVIDER_STATE"


class EvidenceProviderState(StrEnum):
    SCHEDULED = "scheduled"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"
