"""Stable Champion policy failure codes."""

from enum import StrEnum


class ChampionPolicyCode(StrEnum):
    INVALID_VERIFICATION_SET = "CHAMPION_INVALID_VERIFICATION_SET"
    UNSTABLE_ENVIRONMENT = "CHAMPION_UNSTABLE_ENVIRONMENT"
    INSUFFICIENT_IMPROVEMENT = "CHAMPION_INSUFFICIENT_IMPROVEMENT"
